# preload = /home/moep/wallpapers/wallhaven-4d773l.png
# preload = /home/moep/wallpapers/wallhaven-739w33.jpg
#preload = /home/moep/wallpapers/wallhaven-9d8mrx.png
#preload = /home/moep/wallpapers/wallhaven-g78prl.png
#preload = /home/moep/wallpapers/wallhaven-53042.jpg
# preload = /home/moep/wallpapers/wallhaven-5yd6d5.png
# preload = /home/moep/wallpapers/wallhaven-7p5wry.jpg
preload = "/home/moep/wallpapers/wallhaven-7j19zy.png"


#wallpaper = eDP-1,/home/moep/wallpapers/wallhaven-5yd6d5.png
# wallpaper = ,/home/moep/wallpapers/wallhaven-7p5wry.jpg
# wallpaper = eDP-1,/home/moep/wallpapers/wallhaven-4d773l.png
wallpaper { 
  monitor = 
  path = "/home/moep/wallpapers/wallhaven-7j19zy.png"
  fit_mode = "cover"
}

ipc = off
