[colors.bright]
black = "#232628"
blue = "#aae2f1"
cyan = "#66d9ef"
green = "#b7e658"
magenta = "#f92a72"
red = "#fb2f2f"
white = "#f8f8f8"
yellow = "#fbc334"

[colors.normal]
black = "#232628"
blue = "#81a4ff"
cyan = "#66d9ef"
green = "#21d11f"
magenta = "#f92a72"
red = "#fb2f2f"
white = "#cfcfcf"
yellow = "#fbc334"

[colors.primary]
background = "#222222"
foreground = "#ffffff"

[debug]
log_level = "info"

[font]
size = 11

[font.bold]
family = "GohuFont uni14 Nerd Font Mono"

[font.italic]
family = "GohuFont uni14 Nerd Font Mono"

[font.normal]
family = "GohuFont uni14 Nerd Font Mono"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

